### ISSUE TITLE
Inference fails on apple silicon

### ISSUE THREAD

**Issue by joshlatham** [blaise-tk/RVC_CLI#1]
First of all, thank you, this is the first cli for rvc that actually works!! I've been trying all kinds of solutions. Below is a minor enhancement you could make.

The following error is experienced when inferencing on apple silicon:
The operator 'aten::_fft_r2c' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
Voice conversion failed: cannot unpack non-iterable NoneType object

Setting the mps fallback as mentioned works but could be handled in your code.

**Comment by blaise-tk** [comment]
Hello, I am sorry to hear that you are having this problem. Unfortunately I don't have a Mac so I wouldn't be able to try in case to fix it, but if any solution you find works for you and you provide me the code / do a PR I'll be happy to add it! :)

**Comment by cappuch** [comment]
FFT is not supported on MPS [source](https://github.com/pytorch/pytorch/issues/78044)

**Comment by blaise-tk** [comment]
Should be fixed.
