### ISSUE TITLE
API - 

### ISSUE THREAD

**Issue by ART1FICE** [blaise-tk/RVC_CLI#17]
still having issues with the API.  The main infer worked with the same input as the Json bellow. I tried messing around with the format a bit but no luck.

**JSON:**

 {
             "f0up_key": "2",
             "filter_radius": "5",
             "index_rate": "0.1",
             "hop_length": "25",
             "f0method": "dio",
             "input_path": "D:\Projects\VoiceChangerAI\TestFile\testa.wav",
             "output_path": "D:\Projects\VoiceChangerAI\TestFile\output_API.wav",
             "pth_path": "C:\Users\KCLEE\Documents\GitHub\models\LenvalBrown.pth",
             "index_path": "C:\Users\KCLEE\Documents\GitHub\models\LenvalBrown.index",
             "split_audio": "false",
             "f0autotune": "false"
            }

**the console spits out this:**

Traceback (most recent call last):
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\main.py", line 953, in <module>
    main()
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\main.py", line 947, in main
    run_api_script()
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\main.py", line 385, in run_api_script
    subprocess.run(command)
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\env\lib\subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\env\lib\subprocess.py", line 1126, in communicate
    self.wait()
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\env\lib\subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\env\lib\subprocess.py", line 1486, in _wait
    result = _winapi.WaitForSingleObject(self._handle,

**Client side I get a "error 400 - bad request"**

**Comment by blaise-tk** [comment]
Show me the code/client you are using to make an API request.

**Comment by ART1FICE** [comment]
its a unity app (below) I'm fairly confident in the framework working for other POST requests i have used...  - Also i did experiment with the header and got a different error so i don't think its the header... but not sure. -  is there anyway to check if the above  JSON works for you?

> 

          string url = $"http://127.0.0.1:5000/infer";

        using (var postRequest = UnityWebRequest.PostWwwForm(url, "POST"))
        {
            byte[] bodyRaw = System.Text.Encoding.UTF8.GetBytes(json);
            postRequest.uploadHandler = (UploadHandler)new UploadHandlerRaw(bodyRaw);
            postRequest.SetRequestHeader("Content-Type", "application/json");
            

            yield return postRequest.SendWebRequest();

            if (postRequest.result != UnityWebRequest.Result.Success)
            {
                Debug.Log(" POST REQUEST FAILED: " + postRequest.error);
            }  
             else { Debug.Log("SUCCESS"); }
      
}

>

**Comment by blaise-tk** [comment]
I have published a new API system, you can check it out if you want - I'm not sure how it works, let me know if it doesn't work well and feel free to create a PR to improve it. You should use the same parameters you would use with the CLI. 

At http://localhost:8000/docs you can see the documentation
