### ISSUE TITLE
[BUG] Batch Conversion on Apple Silicon Mac

### ISSUE THREAD

**Issue by Chilluminati91** [blaise-tk/RVC_CLI#18]
I've got Applio running on my M2 Max Mac Studio but Batch Conversion is not working. To get further information I cloned this git here and tried the CLI batch conversion, which also does not work. Single conversion works fine with CLI and Applio.

This is my single conversion cmd, which results in a working file:
`python main.py infer --f0up_key "0" --filter_radius "3" --index_rate "0.8" --hop_length "64" --split_audio "True" --f0autotune "False" --f0method "rmvpe" --input_path "/Users/liam/Music/RVC/city_of_angels/hmmmh.wav" --output_path "/Users/liam/Downloads/test/test.wav" --pth_path "/Applications/RVC_Applio/logs/40k_natedogg_super/40k_natedogg_super.pth" --index_path "/Applications/RVC_Applio/logs/40k_natedogg_super/40k_natedogg_super_clean.index"`

This is batch-conversion, which results in an error, no matter if rms_mix_rate and other parameters are included in the cmd or not:
`python main.py batch_infer --f0up_key "0" --filter_radius "3" --index_rate "0.8" --hop_length "64" --split_audio "True" --f0autotune "False" --f0method "rmvpe" --input_folder "/Users/liam/Music/RVC/love_me_down/ValYoung" --output_folder "/Users/liam/Downloads/test" --pth_path "/Applications/RVC_Applio/logs/40k_natedogg_super/40k_natedogg_super.pth" --index_path "/Applications/RVC_Applio/logs/40k_natedogg_super/40k_natedogg_super_clean.index" --rms_mix_rate "0.0"`

The conversion fails with the following error:
```
Inferring /Users/liam/Music/RVC/love_me_down/ValYoung/Ladada_1.wav.wav...
No supported Nvidia GPU found
Traceback (most recent call last):
  File "/Users/liam/Downloads/RVC_CLI/rvc/infer/infer.py", line 229, in <module>
    rms_mix_rate = float(sys.argv[12])
ValueError: could not convert string to float: 'True'
```

Seems like rms_mix_rate=True is sneaking in somewhere, and resulting in an error when converted to float. But where is it coming from? I removed all arguments that use True/False from the cmd, but it still ends up with this error.

**Comment by Chilluminati91** [comment]
Okay, I have no idea what I am doing here or why, but I managed to get it to work by replacing parts of the run_batch_infer_script function in "main.py".
Replace lines 112 to 128 with a copy of the single infer command.

From:

```
command = [
                "python",
                infer_script_path,
                f0up_key,
                filter_radius,
                index_rate,
                rms_mix_rate,
                protect,
                hop_length,
                f0method,
                input_path,
                output_path,
                pth_path,
                index_path,
                split_audio,
                f0autotune,
            ]
```

To:

```
command = [
                "python",
                *map(
                    str,
                    [
                        infer_script_path,
                        f0up_key,
                        filter_radius,
                        index_rate,
                        hop_length,
                        f0method,
                        input_path,
                        output_path,
                        pth_path,
                        index_path,
                        split_audio,
                        f0autotune,
                        rms_mix_rate,
                        protect,
                    ],
                ),
            ]
```

**Comment by aitronssesin** [comment]
I think you have like an outdated version because in the latest is working and that code is already added
![image](https://github.com/blaise-tk/RVC_CLI/assets/74368135/30817c19-d150-42e3-a732-0f02e19d3854)
y added

**Comment by Chilluminati91** [comment]
Pulled the latest changes today, code has been changed but it seems like the bug is still present now.

```
Detected 4 audio files for inference.
Inferring /Users/liam/Music/RVC/love_me_down/ValYoung/Ladada.wav.wav...
No supported Nvidia GPU found
Traceback (most recent call last):
  File "/Users/liam/Downloads/RVC_CLI/rvc/infer/infer.py", line 246, in <module>
    rms_mix_rate = float(sys.argv[12])
ValueError: could not convert string to float: 'True'
```

**Comment by blaise-tk** [comment]
I'll check.

**Comment by blaise-tk** [comment]
The "rms_mix_rate" parameter must be a numerical value ranging from 0.0 to 1.0. If you're unsure of what value to set, you can omit the argument, and the default value will be used.

![image](https://github.com/blaise-tk/RVC_CLI/assets/133521603/483daee5-520b-4960-9b15-0d7e4c701d2e)

**Comment by Chilluminati91** [comment]
Checked that already, it doesnt matter wether it is ommitted or correctly used, it always ends with the ValueError string to float "true".
If i input a non-working value like "2" it outputs the typical help info ofc.

**Comment by blaise-tk** [comment]
Ready, fixed.

**Comment by Chilluminati91** [comment]
Awesome, working now. Thanks!
