### ISSUE TITLE
IP and PORT change for API

### ISSUE THREAD

**Issue by Artem-IDA** [blaise-tk/RVC_CLI#19]
Hello, I didn’t find any other contacts, so I’ll write the problem here.
## Question context:
I'm trying to write an application in C# (WinForms) using your solution. I am weak in programming, outside the zone of simple C# applications, but I was interested in the functionality of the RVC library. I want to try to establish interaction with the RVC by organizing a server and sending requests to it from clients from the global network. But I encountered a problem when the API server is launched on a local machine, where there is a suitable video card for work, but on the machine with which the application is being developed - there is no. And to establish communication with my “server” where your solution will be deployed, I tried to change the server launch parameters to a local IP (192.168.x.x) and another port, but failed.
## The main point of the question:
Can I somehow use launch parameters (for example the main.py api [-ip or -port] file) to change the parameters of the API server (uvicorn server)?
If not, is it possible to add such functionality to the "main.py api" command?

**Comment by blaise-tk** [comment]
yeah give me some minutes and i upload a new commit with this, thanks for the suggestion and sorry 😄

**Comment by Artem-IDA** [comment]
Thanks a lot. Updated and checked. The server starts with the specified custom IP and port parameters.

**Comment by blaise-tk** [comment]
❤️ Thanks for using my repo
