### ISSUE TITLE
Stuff to improve GUI wise or ya get what i mean :3

### ISSUE THREAD

**Issue by litsa-the-dancer** [blaise-tk/RVC_CLI#37]
So first things first, infer section looks alright. moving on to training u guys can def improve some stuff on there:
1. Preprocess Dataset: i believe you guys should set the preset sample rate to 32k and not 40k
2. Extract Features: eradicate v1, its outdated and uses a smaller hubert (i think) but regardless it lacks in dynamics much more than the v2 arch we have for rvc so yeah u can just remove the option of choosing versions and auto set it to v2.
the rest looks fine for now, i really like it at least. One thing u can also add though is model fusion and all the other stuff the gui has like ckpt processing and so on and so forth. Other than that it works wonderfully :3

**Comment by blaise-tk** [comment]
We don't have any default parameter in the preprocess
![image](https://github.com/blaise-tk/RVC_CLI/assets/133521603/7d187bae-4b25-4c2a-9bae-1221dea4eece)

all the options like the ckpt and the model fusion we have already added

**Comment by litsa-the-dancer** [comment]
> Owner

Ahh i see, well i assumed that cuz thats what was preselected for me. Anyhow i still think its a good idea to have it auto set to 32k
