### ISSUE TITLE
[BUG] '<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by kronkinatorix** [blaise-tk/RVC_CLI#45]
**Describe the bug**
It looks like the value of args.protect isn't being converted properly to a float. I've tried converting the arg to a float directly but it produces errors related tot he tensor size in torch.from_numpy(npy).unsqueeze(0).to(self.device) * index_rate + (1 - index_rate) * feats. Fiddled with a bit but couldn't get anything worthwhile to come out. 

**To Reproduce**
$ python3 main.py batch_infer --f0up_key 5 --filter_radius 4 --index_rate 0.9 --hop_length 128 --rms_mix_rate 1.0 --protect 0.4 --f0autotune True --f0method rmvpe --input_folder "/home/mb/Desktop/" --output_folder "/home/mb/Desktop/" --pth_path "/home/mb/Desktop/Retrieval-based-Voice-Conversion-WebUI/assets/weights/compooter.pth" --index_path "/home/mb/Desktop/Retrieval-based-Voice-Conversion-WebUI/logs/compooter/trained_IVF256_Flat_nprobe_1_compooter_v2.index" --export_format WAV

changing the value of protect doesn't seem to change the error. 

**Expected behavior**
For the inference to happen correcty 

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - Linux Mint 21 runningg kernel 6.5.0-26-generic
 - Firefox?

**Additional context**

**Comment by blaise-tk** [comment]
put all the values as an string with "X"

**Comment by kronkinatorix** [comment]
The error still happened when I was attempting to debug the code with clargs that were explicitly strings in VS code. 

Still happens with:
