### ISSUE TITLE
[BUG] '<' not supported between instances of 'str' and 'float' / No output file

### ISSUE THREAD

**Issue by ejwright** [blaise-tk/RVC_CLI#46]
**Describe the bug**
During infer an error/warning is reported, " '<' not supported between instances of 'str' and 'float' "
and no output file is written despite the output saying it is. 

**To Reproduce**
Run the command
```
PS M:\LLMs\tts\RVC_CLI> .\env\python.exe main.py infer `
>> --index_path '.\rvcs\test0.index' `
>> --pth_path '.\rvcs\test0.pth' `
>> --input_path '.\output.wav' `
>> --output_path 'M:\LLMs\tts\RVC_CLI\output-rvc.wav'
<All keys matched successfully>
'<' not supported between instances of 'str' and 'float'
Conversion completed. Output file: 'M:\LLMs\tts\RVC_CLI\output-rvc.wav' in 2.22 seconds.
PS M:\LLMs\tts\RVC_CLI>
```

**Expected behavior**
An output file processed with the supplied pth/index

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
Windows 11 

**Additional context**
If I checkout tag 1.1.2 it all works

**Comment by blaise-tk** [comment]
can you show me your cmd?

**Comment by ejwright** [comment]
> can you show me your cmd? an screenshot 

Sure, command is what I have above.. here is the screen shot

![image](https://github.com/blaise-tk/RVC_CLI/assets/1383783/7e2ca208-a517-4fdc-904b-854586b0a6de)

**Comment by ejwright** [comment]
> put all the args in the same line and the full path to the audios and models

I tried that, but I'm still getting an error --- I tried in both Powershell and the basic command line

 I also did a clean install and tried again, same issue... 

PowerShell

![image](https://github.com/blaise-tk/RVC_CLI/assets/1383783/f5ed1010-aad3-4573-9f63-bd1e38422607)

DOS
![image](https://github.com/blaise-tk/RVC_CLI/assets/1383783/52ddd7cf-012b-499b-8f92-c00f603bd6f4)

**Comment by blaise-tk** [comment]
in the second one you are not passing the args as an string

**Comment by blaise-tk** [comment]
i don't have this issue, i literally copied your command and is fine, let me know if you find any solution

**Comment by ejwright** [comment]
No solution, but for what its worth, I ran a trace and this is the line causing the exception.. 

https://github.com/blaise-tk/RVC_CLI/blame/176d9e0f459eee2bcc52fe6dfa6953ecf1b0bfc5/rvc/infer/pipeline.py#L396

        if protect < 0.5 and pitch != None and pitchf != None:

**Comment by blaise-tk** [comment]
ok, i'll check it tomorrow

**Comment by ejwright** [comment]
Cool, here is what I see on my trace

![image](https://github.com/blaise-tk/RVC_CLI/assets/1383783/81066b93-45ed-489c-9deb-5a0cbec65341)

**Comment by blaise-tk** [comment]
fixed.
