### ISSUE TITLE
split_audio does not seem to work?

### ISSUE THREAD

**Issue by beatsgithub** [blaise-tk/RVC_CLI#5]
Setting to True or False always results on in the same output.wav? how can I get the voice swapped output combined with the original instrumental ? Thanks. This one has been the easiest to use tool so far.

**Comment by blaise-tk** [comment]
Split audio means that in the process of inference, it splits the audio into smaller pieces to get a better result many times over

**Comment by ghbeats** [comment]
got it thanks @blaise-tk for the prompt the reply, what would be the recommended approach to merging the vocals back in to the original?
