### ISSUE TITLE
Issue with Model Output Generating Noise

### ISSUE THREAD

**Issue by Mirrormsk** [blaise-tk/RVC_CLI#54]
Issue with Model Output Generating Noise

The model is training successfully, but when attempting to process a file, the output consists only of squeaks and noise. This issue persists even when using alternative models; the resulting audio remains distorted. Interestingly, utilizing a model trained in a different version of RVC yields normal functioning.
Another instance of RVC works fine in this machine.

What could be the underlying cause? Various output file formats have been experimented with to no avail.

Using VDS
 - OS: Ubuntu 20.04
- RTX 3060

**Comment by blaise-tk** [comment]
If you don't send me the audio, hard to say what's happening

**Comment by Mirrormsk** [comment]
> If you don't send me the audio, hard to say what's happening

Of course. Example:
https://drive.google.com/file/d/1cvg81Ik6NmxXSFiZsSmXjvGjsrsEud5A/view?usp=share_link

**Comment by Mirrormsk** [comment]
> `git checkout 4e9788132598887783df88f996db03976b2db45d` fixed the problem for me

That worked, thank you!

**Comment by Mirrormsk** [comment]
> `git checkout 4e9788132598887783df88f996db03976b2db45d` fixed the problem for me

on this commit works great.
