### ISSUE TITLE
Training args

### ISSUE THREAD

**Issue by aditi-916** [blaise-tk/RVC_CLI#6]
The voice is getting distorted when chunks are made resulting in robotic voice in output

**Comment by blaise-tk** [comment]
you mean using audio split?

**Comment by aditi-916** [comment]
The output result and also when I heard the audio that it divided into chunks it was also very robotic

**Comment by blaise-tk** [comment]
with what f0 method?

**Comment by aditi-916** [comment]
rmvpe

**Comment by blaise-tk** [comment]
can you check with other models? i didnt have any problems, or if you can also upload the results to somewhere

**Comment by aditi-916** [comment]
https://drive.google.com/drive/folders/1ZB1oz5j5AGA4eREWdD-8VH37yJZQJIOr?usp=drive_link 
this is through rmvpe model
the params i used for training and inference-
python main.py train "PREETI" v2 50 False True 200 48000 8 0 True False False

python main.py infer 0 0 0.66 20 rmvpe "C:\Users\Aditi\Desktop\Aditi_work\RVC\RVC_CLI\target\female_english.wav" "output\preeti_fe_150epochs.wav" "C:\Users\Aditi\Desktop\Aditi_work\RVC\RVC_CLI\logs\PREETI_150e.pth" "C:\Users\Aditi\Desktop\Aditi_work\RVC\RVC_CLI\logs\PREETI\trained_IVF1643_Flat_nprobe_1_v2.index" True True

**Comment by blaise-tk** [comment]
ok, i’ll check it

**Comment by blaise-tk** [comment]
your model is only 150 epochs, did you try with an another hq model?

**Comment by aditi-916** [comment]
used rmvpe till 250 epochs when i used it via gui 150 epochs were enough for good results

**Comment by smartinezbragado** [comment]
I am also getting robotic results. I replicated the inference in the webui and the results were much better. Do you know what are we missing?

**Comment by blaise-tk** [comment]
That error occurs because the training parameters are not set correctly - I will make a new way to set the parameters, in the meantime you can use it in webui form using Applio.

**Comment by computersrmyfriends** [comment]
I get the same issue not only during training but a similar issue during inference also
