### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ART1FICE** [blaise-tk/RVC_CLI#8]
I'm having some issues with the API call (internal server error) - I'm assuming its the syntax of the JSON at this point, ive messed around a bit but keeps returning in error. Here is how the Json is syntaxed atm:
{
             "f0up_key": 0,
             "filter_radius": 5,
             "index_rate": 0.5,
             "hop_length": 256,
             "f0method": "rmvpe",
             "input_path": "D:\Projects\VoiceChangerAI\TestFile\testa.wav",
             "output_path": "D:\Projects\VoiceChangerAI\TestFile\output.wav",
             "pth_file": "LB.pth",
             "index_path": "LB.index",
             "split_audio": false,
            }

have "LB.pth" and the index in the "RVC_CLI\models" folder currently?  

Thanks for any help - I'm total narb with this stuff >_<

**Comment by ART1FICE** [comment]
i tried full paths to the pth/index files, and also tried to remove quotes from "rmvpe" -  now i'm less sure its syntax and maybe something else im doing wrong - but still would be nice to know for sure -  **Thanks** ^_^

**Comment by ART1FICE** [comment]
RIGHT - So, I did get the infer working threw the CLI which helped me with the syntax (current json below)...  so now i really dunno what the issue is,  I noticed the "f0_autotune" param was added so tried with and without adding that... but still just:

 "POST /infer HTTP/1.1" 500 - 

Latest JSON, still not working -  is as follows:
{
             "f0up_key": 0,
             "filter_radius": 5,
             "index_rate": 0.5,
             "hop_length": 256,
             "f0method": "harvest",
             "input_path": "D:\Projects\VoiceChangerAI\TestFile\testa.wav",
             "output_path": "D:\Projects\VoiceChangerAI\TestFile\output.wav",
             "pth_file": "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\models\LB.pth",
             "index_path": "C:\Users\KCLEE\Documents\GitHub\RVC_CLI\models\LB.index",
             "split_audio": false
            }

**Comment by blaise-tk** [comment]
Just wait for me to update the API, there are a few things missing,

**Comment by blaise-tk** [comment]
Check the last update :)
